server.port=8080
spring.application.name=customer-app
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.jackson.time-zone=Europe/Samara
spring.mvc.static-path-pattern=/**
spring.resources.static-locations=classpath:/static/
server.servlet.session.cookie.name=CUSTOMER_SESSIONID